### ISSUE TITLE
Add RSS Feed

### ISSUE THREAD

**Issue by Snugug** [Snugug/blog#2]
Add an RSS feed to the site. Link should go in #1

**Comment by patik** [comment]
Full content, preferably. When I know I'm going to be offline (flight, etc) I can refresh my reader app and have it cache images. For videos it's nice to be able to watch it as soon as I come across it in the article rather than scrolling up, clicking on the title to open your site, waiting for it to load, scrolling back down to the video, etc.

RSS vs Atom — I haven't seen an app that can't handle both, so as a user I don't have a preference. I have no idea which technology my favorite sites use.

**Comment by Snugug** [comment]
This is done!
